
### Test Register

POST {{host}}/register
Content-Type: application/json
Accept: application/json

{
  "name": "John Doe",
  "email": "johndoe@email.com",
  "password": "johndoe123"
}

### Test Register Invalid Data

POST {{host}}/register
Content-Type: application/json
Accept: application/json

{
  "name": "",
  "email": "",
  "password": ""
}

### Test Login Admin

POST {{host}}/login
Accept: application/json
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "admin123"
}

### Test Login User

POST {{host}}/login
Accept: application/json
Content-Type: application/json

{
  "email": "johndoe@email.com",
  "password": "johndoe123"
}

### Test Login Wrong Password

POST {{host}}/login
Accept: application/json
Content-Type: application/json

{
  "email": "johndoe@email.com",
  "password": "12345"
}

### Test Admin Area

GET {{host}}/admin
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJpc3MiOiJAbHV0aGZpcHVuIiwicm9sZXMiOiJST0xFX0FETUlOIiwiaWF0IjoxNjYzNzYzNDIwLCJleHAiOjE2NjM3NjM0ODB9.b3vOQkRsS8p2WvXCXRnADimnp4kDaMa4ID_uWbl3o57sj11WyToJ649WXJgtMJ19-z9APiTLxVC1B005wSXixA
