
### Test Register

POST {{host}}/register
Content-Type: application/json
Accept: application/json

{
  "name": "John Doe",
  "email": "johndoe@email.com",
  "password": "johndoe123"
}

### Test Register Invalid Data

POST {{host}}/register
Content-Type: application/json
Accept: application/json

{
  "name": "",
  "email": "",
  "password": ""
}

### Test Login

POST {{host}}/login
Accept: application/json
Content-Type: application/json

{
  "email": "johndoe@email.com",
  "password": "johndoe123"
}

### Test Login Wrong

POST {{host}}/login
Accept: application/json
Content-Type: application/json

{
  "email": "johndoe@email.com",
  "password": "12345"
}

### Test Admin Area

GET {{host}}/admin
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJqb2huZG9lQGVtYWlsLmNvbSIsImlzcyI6IkBsdXRoZmlwdW4iLCJpYXQiOjE2NjM3MTI0ODEsImV4cCI6MTY2MzcxMjU0MX0.I9LrI7t7iRPRguoRl03dMwapk7gBGkNdg_9jS-VO0E4OSe4m6zcOdHgmXZZFKxp4eKU5iPY0EhvEyycHf7gpfg
